DEFAULT_USER=`whoami`
DOTFILES_PATH=$HOME/.$DEFAULT_USER/dotfiles
source $DOTFILES_PATH/environment_vars.zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
POWERLEVEL9K_MODE='awesome-fontconfig'
ZSH_THEME="powerlevel9k/powerlevel9k"

source $DOTFILES_PATH/zsh_additional_confs.zsh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nano'
else
  export EDITOR='nano'
fi

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"


source $DOTFILES_PATH/powerlevel9k.zsh
source $DOTFILES_PATH/aliases.zsh
source $DOTFILES_PATH/functions.zsh
source $DOTFILES_PATH/environment_vars.zsh

eval "$(pyenv init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/adricu/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/adricu/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/adricu/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/adricu/google-cloud-sdk/completion.zsh.inc'; fi
